interface IImage {
	id: number;
	name: string;
	image: string;
}
// https://starwars.fandom.com/wiki/Luke_Skywalker
export const STAR_WARS_IMAGES: IImage[] = [
    // PAGE 1
    {id: 1, name: 'Luke Skywalker', image: 'lukeSkywalker.webp'},
    {id: 2, name: 'C-3PO', image: 'c3po.jpeg'},
    {id: 3, name: 'R2-D2', image: 'r2D2.jpeg'},
    {id: 4, name: 'Darth Vader', image: 'anakinSkywalker.webp'},
    {id: 5, name: 'Leia Organa', image: 'leiaOrgana.webp'},
    {id: 6, name: 'Owen Lars', image: 'owenLars.webp'},
    {id: 7, name: 'Beru Whitesun lars', image: 'beruWhitesunLars.webp'},
    {id: 8, name: 'R5-D4', image: 'r5D4.webp'},
    {id: 9, name: 'Biggs Darklighter', image: 'biggsDarklighter.webp'},
    {id: 10, name: 'Obi-Wan Kenobi', image: 'obiWan.webp'},
    //PAGE 2
    {id: 11, name: 'Anakin Skywalker', image: 'anakinSkywalker.webp'},
    {id: 12, name: 'Wilhuff Tarkin', image: 'wilhuffTarkin.webp'},
    {id: 13, name: 'Chewbacca', image: 'chewbacca.webp'},
    {id: 14, name: 'Han Solo', image: 'hanSolo.webp'},
    {id: 15, name: 'Greedo', image: 'greedo.webp'},
    {id: 16, name: 'Jabba Desilijic Tiure', image: 'jabbaTiure.webp'},
    {id: 17, name: 'Wedge Antilles', image: 'wedgeAntilles.webp'},
    {id: 18, name: 'Jek Tono Porkins', image: 'jekPorkins.webp'},
    {id: 19, name: 'Yoda', image: 'yoda.webp'},
    {id: 20, name: 'Palpatine', image: 'palpatine.webp'},
    // PAGE 3
    {id: 21,name: 'Boba Fett', image: 'bobaFett.webp'},
    {id: 22,name: 'IG-88', image: 'iG88B.webp'},
    {id: 23,name: 'Bossk', image: 'bossk.webp'},
    {id: 24,name: 'Lando Calrissian', image: 'landoCalrissian.webp'},
    {id: 25,name: 'Lobot', image: 'lobot.webp'},
    {id: 26,name: 'Ackbar', image: 'ackbar.webp'},
    {id: 27,name: 'Mon Mothma', image: 'monmothma.webp'},
    {id: 28,name: 'Arvel Crynyd', image: 'arvelCrynyd.webp'},
    {id: 29,name: 'Wicket Systri Warrick', image: 'wicketWarrick.webp'},
    {id: 30,name: 'Nien Nunb', image: 'nienNunb.webp'},
    // PAGE 4
    {id: 31,name: 'Qui-Gon Jinn', image: 'nienNunb.webp'},
    {id: 32,name: 'Nute Gunray', image: 'nuteGunray.webp'},
    {id: 33,name: 'Finis Valorum', image: 'finisValorum.webp'},
    {id: 34,name: 'Padmé Amidala', image: 'padmeAmidala.webp'},
    {id: 35,name: 'Jar Jar Binks', image: 'jarJarBinks.webp'},
    {id: 36,name: 'Roos Tarpals', image: 'roosTarpals.webp'},
    {id: 37,name: 'Rugor Nass', image: 'rugorNass.webp'},
    {id: 38,name: 'Ric Olié', image: 'ricOlie.webp'},
    {id: 39,name: 'Watto', image: 'watto.webp'},
    {id: 40,name: 'Sebulba', image: 'sebulba.webp'},
    // PAGE 5
    {id: 41,name: 'Quarsh Panaka', image: 'quarshPanaka.webp'},
    {id: 42,name: 'Shmi Skywalker', image: 'shmiSkywalker.webp'},
    {id: 43,name: 'Darth Maul', image: 'darthMaul.webp'},
    {id: 44,name: 'Bib Fortuna', image: 'bibFortuna.webp'},
    {id: 45,name: 'Ayla Secura', image: 'aylaSecura.webp'},
    {id: 46,name: 'Ratts Tyerel', image: 'rattsTyerel.webp'},
    {id: 47,name: 'Dud Bolt', image: 'dudBolt.webp'},
    {id: 48,name: 'Gasgano', image: 'gasgano.webp'},
    {id: 49,name: 'Ben Quadinaros', image: 'benQuadinaros.webp'},
    {id: 50,name: 'Mace Windu', image: 'maceWindu.webp'},
    // PAGE 6
    {id: 51,name: 'Ki-Adi-Mundi', image: 'kiAdiMundi.webp'},
    {id: 52,name: 'Kit Fisto', image: 'kitFisto.webp'},
    {id: 53,name: 'Eeth Koth', image: 'eethKoth.webp'},
    {id: 54,name: 'Adi Gallia', image: 'adiGallia.webp'},
    {id: 55,name: 'Saesee Tiin', image: 'saeseeTiin.webp'},
    {id: 56,name: 'Yarael Poof', image: 'yaraelPoof.webp'},
    {id: 57,name: 'Plo Koon', image: 'ploKoon.webp'},
    {id: 58,name: 'Mas Amedda', image: 'masAmedda.webp'},
    {id: 59,name: 'Gregar Typho', image: 'gregarTypho.webp'},
    {id: 60,name: 'Cordé', image: 'corde.webp'},
    // PAGE 7
    {id: 61,name: 'Cliegg Lars', image: 'clieggLars.webp'},
    {id: 62,name: 'Poggle the Lesser', image: 'poggleTheLesser.webp'},
    {id: 63,name: 'Luminara Unduli', image: 'luminaraUnduli.webp'},
    {id: 64,name: 'Barriss Offee', image: 'barrissOffee.webp'},
    {id: 65,name: 'Dormé', image: 'dorme.webp'},
    {id: 66,name: 'Dooku', image: 'dooku.webp'},
    {id: 67,name: 'Bail Prestor Organa', image: 'bailPrestorOrgana.webp'},
    {id: 68,name: 'Jango Fett', image: 'jangoFett.webp'},
    {id: 69,name: 'Zam Wesell', image: 'zamWesell.webp'},
    {id: 70,name: 'Dexter Jettster', image: 'dexterJettster.webp'},
    // PAGE 8
    {id: 71,name: 'Lama Su', image: 'lamaSu.webp'},
    {id: 72,name: 'Taun We', image: 'taunWe.webp'},
    {id: 73,name: 'Jocasta Nu', image: 'jocastaNu.webp'},
    {id: 74,name: 'R4-P17', image: 'r4P17.webp'},
    {id: 75,name: 'Wat Tambor', image: 'watTambor.webp'},
    {id: 76,name: 'San Hill', image: 'sanHill.webp'},
    {id: 77,name: 'Shaak Ti', image: 'shaakTi.webp'},
    {id: 78,name: 'Grievous', image: 'grievous.webp'},
    {id: 79,name: 'Tarfful', image: 'tarfful.webp'},
    {id: 80,name: 'Raymus Antilles', image: 'raymusAntilles.webp'},
    // PAGE 9
    {id: 81,name: 'Sly Moore', image: 'slyMoore.webp'},
    {id: 82,name: 'Tion Medon', image: 'tionMedon.webp'},
];
